## cartridge.properties for cartridge plugin_customer_coupons
    #Wed Sep 02 2026 20:47:58 GMT+0900 (日本標準時)
    demandware.cartridges.plugin_customer_coupons.multipleLanguageStorefront=true
    demandware.cartridges.plugin_customer_coupons.id=plugin_customer_coupons
    